# Generated by Django 3.1.3 on 2020-12-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='fuel_consumption',
            new_name='fuel_tank',
        ),
    ]
