# Generated by Django 3.1.3 on 2020-12-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20201215_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_posted',
            field=models.DateField(),
        ),
    ]
